CREATE TABLE EMPLOYEE(
empid INT PRIMARY KEY Auto_Increment,
Name VARCHAR(100) NOT NULL,
Salary decimal(10,2) NOT NULL,
Designation VARCHAR(50) NOT NULL,
DoJ DATE NOT NULL,
Location VARCHAR(100) NOT NULL
);
INSERT INTO EMPLOYEE(NAME, Salary, Designation, DoJ, Location) values('PRAVEEN', 7777, 'TECH', '2020-08-07','CHENNAI'),
('ramesh',88888, 'TECH', '2020-08-07','CHENNAI'),
('vicky', 7777, 'TECH', '2020-08-07','CHENNAI'),
('VADAKS', 99000, 'TECH', '2020-08-07','CHENNAI');
select * FROM EMPLOYEE;

update EMPLOYEE set NAME='RAJESH' WHERE EMPID=2;
select * FROM EMPLOYEE;

UPDATE EMPLOYEE SET SALARY=99999 WHERE EMPID=3;
select * FROM EMPLOYEE;

ALTER TABLE EMPLOYEE ADD EMAILID VARCHAR(100) ;
select * FROM EMPLOYEE;

DELETE FROM EMPLOYEE WHERE EMPID=1;
select * FROM EMPLOYEE;

SELECT COUNT(LOCATION) as count FROM EMPLOYEE WHERE LOCATION='CHENNAI' ;
SELECT avg(SALARY) as average FROM EMPLOYEE;
SELECT sum(salary) as total from employee;
SELECT max(salary) as highest from employee;